[[PhreeqcRM]]
arch = "aarch64"
git-tree-sha1 = "be477ed3816ab3828d993863acd26140976d6721"
libgfortran_version = "5.0.0"
os = "macos"

    [[PhreeqcRM.download]]
    sha256 = "4830d157d895baccd4883b5f53600217ba67a8ace7fbabb88efd94a9d1c1eb76"
    url = "https://github.com/boriskaus/PhreeqcRM_jll.jl/releases/download/PhreeqcRM-v3.8.2+0/PhreeqcRM.v3.8.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PhreeqcRM]]
arch = "x86_64"
git-tree-sha1 = "8e3bb4486ce6977e31247349a954ca276278642d"
libgfortran_version = "4.0.0"
os = "macos"

    [[PhreeqcRM.download]]
    sha256 = "7f458d5dc8e39a001bacfa99e58532221ae38c96996907139222defcbdb07b03"
    url = "https://github.com/boriskaus/PhreeqcRM_jll.jl/releases/download/PhreeqcRM-v3.8.2+0/PhreeqcRM.v3.8.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PhreeqcRM]]
arch = "x86_64"
git-tree-sha1 = "8e3bb4486ce6977e31247349a954ca276278642d"
libgfortran_version = "5.0.0"
os = "macos"

    [[PhreeqcRM.download]]
    sha256 = "7f458d5dc8e39a001bacfa99e58532221ae38c96996907139222defcbdb07b03"
    url = "https://github.com/boriskaus/PhreeqcRM_jll.jl/releases/download/PhreeqcRM-v3.8.2+0/PhreeqcRM.v3.8.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PhreeqcRM]]
arch = "x86_64"
git-tree-sha1 = "59893d87c9896eafbaab985f304234356f6ff8c9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PhreeqcRM.download]]
    sha256 = "0beb9b3449486501a451446a700c4c7f30e14ec0aea0165ff6e43f67fa36bf8d"
    url = "https://github.com/boriskaus/PhreeqcRM_jll.jl/releases/download/PhreeqcRM-v3.8.2+0/PhreeqcRM.v3.8.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PhreeqcRM]]
arch = "x86_64"
git-tree-sha1 = "90b5ddc373b9e60fb39d7c0ad378cb57955c2332"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PhreeqcRM.download]]
    sha256 = "96c4fb31b0572d8d976880056a2cd243c7f3a8abf47c73421461c86a32ef09a8"
    url = "https://github.com/boriskaus/PhreeqcRM_jll.jl/releases/download/PhreeqcRM-v3.8.2+0/PhreeqcRM.v3.8.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PhreeqcRM]]
arch = "x86_64"
git-tree-sha1 = "495e75b7f449f0c28b68561ced10fc7dd23a37a6"
libgfortran_version = "4.0.0"
os = "windows"

    [[PhreeqcRM.download]]
    sha256 = "4c660feffdd611e46f90e1f4444fd04d271a5aea053177589fe8ef7820adccc0"
    url = "https://github.com/boriskaus/PhreeqcRM_jll.jl/releases/download/PhreeqcRM-v3.8.2+0/PhreeqcRM.v3.8.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PhreeqcRM]]
arch = "x86_64"
git-tree-sha1 = "f2e170d39b55caf66c1ecc5666dbf83e85c7dc74"
libgfortran_version = "5.0.0"
os = "windows"

    [[PhreeqcRM.download]]
    sha256 = "2d2740835d72c0805195fd63a795d4055fcadd18c7c9ca1a5984a832e44f2725"
    url = "https://github.com/boriskaus/PhreeqcRM_jll.jl/releases/download/PhreeqcRM-v3.8.2+0/PhreeqcRM.v3.8.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
