# Autogenerated wrapper script for PhreeqcRM_jll for x86_64-linux-gnu-libgfortran4
export libPhreeqcRM

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("PhreeqcRM")
JLLWrappers.@declare_library_product(libPhreeqcRM, "libPhreeqcRM.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libPhreeqcRM,
        "lib/libPhreeqcRM.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
