# Autogenerated wrapper script for PhreeqcRM_jll for x86_64-w64-mingw32-libgfortran5
export libPhreeqcRM

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("PhreeqcRM")
JLLWrappers.@declare_library_product(libPhreeqcRM, "libPhreeqcRM.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libPhreeqcRM,
        "bin\\libPhreeqcRM.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
