# Autogenerated wrapper script for PhreeqcRM_jll for x86_64-apple-darwin-libgfortran5
export libPhreeqcRM

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("PhreeqcRM")
JLLWrappers.@declare_library_product(libPhreeqcRM, "@rpath/libPhreeqcRM.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libPhreeqcRM,
        "lib/libPhreeqcRM.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
